# Generated by Django 2.0.2 on 2018-04-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0004_auto_20180416_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(choices=[('crocin', 'Crocin'), ('crocinadv', 'Crocin Advanced'), ('crocincaf', 'Crocin Cold And Flu')], default='crocin', max_length=2)),
                ('answer', models.TextField(max_length=400)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoint.Patient')),
            ],
        ),
    ]
