# Generated by Django 2.0.2 on 2018-04-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0006_auto_20180420_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medicine',
            field=models.CharField(max_length=100),
        ),
    ]
