# Generated by Django 2.0.2 on 2018-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0007_auto_20180420_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='answer',
            field=models.TextField(default='Bye', max_length=400),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine',
            field=models.CharField(default='crocin', max_length=100),
        ),
    ]
