# Generated by Django 2.0.2 on 2018-04-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0008_auto_20180420_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
