# Generated by Django 2.0.2 on 2018-04-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0009_auto_20180420_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='answer',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medicine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoint.SignUp'),
        ),
    ]
