# Generated by Django 2.0.1 on 2018-04-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0010_auto_20180421_0007'),
        ('appoint', '0006_auto_20180420_1222'),
    ]

    operations = [
    ]
